### ISSUE TITLE
Check whether a communicator/window/file is revoked

### ISSUE THREAD

**Issue by wesbland** [mpiwg-ft/ft-issues#1]
There have been multiple requests to have some new functions in ULFM that would look like:

```
MPI_COMM_IS_REVOKED(MPI_Comm comm, int *bool);
MPI_WIN_IS_REVOKED(MPI_Win win, int *bool);
MPI_FILE_IS_REVOKED(MPI_File file, int *bool);
```

There has been discussion in the past about thread safety issues that arise from this. Specifically, that a user might have received `MPI_ERR_REVOKED` in one thread but not another. Aurelien suggested that users could set an attribute on the communication object to track this.

However, given the number of times this has come up, this convenience function might be worth adding the extra APIs. I think the thread safety issue is ok as long as we're clear that these functions will never return true until some thread has returned `MPI_ERR_REVOKED` to the user.

**Comment by abouteiller** [comment]
History of the issue found here: https://bitbucket.org/bosilca/mpi3ft/issues/6/introspection-for-comm_revoked

**Comment by abouteiller** [comment]
Tentative text added in branch https://github.com/mpiwg-ft/mpi-standard/tree/ulfm/isrevoked

**Comment by abouteiller** [comment]
Branch has been slurped in the ulfm/main
