### ISSUE TITLE
Broken link to MPI standard in README

### ISSUE THREAD

**Issue by rouson** [mpiwg-ft/ft-issues#12]
The [mpiwg-ft/mpistandard](http://github.com/mpiwg-ft/mpi-standard) link in the README.md file is broken.

**Comment by wesbland** [comment]
The link isn't actually broken. It just points to a private repository. We have to keep it that way because of MPI Forum rules. I should update the readme to reflect that.

If you're interested in participating in the working group, you can contact me directly and I can add you.
