### ISSUE TITLE
MPI_COMM_IAGREE interface changes

### ISSUE THREAD

**Issue by nathanweeks** [mpiwg-ft/ft-issues#13]
The February 21, 2017 ULFM draft has the following Fortran 2008 interface for MPI_COMM_IAGREE:

```
MPI_Comm_iagree(comm, flag, req, ierror)
    TYPE(MPI_Comm), INTENT(IN) :: comm
    INTEGER, INTENT(INOUT) :: flag
    TYPE(MPI_Request), INTENT(OUT) :: req 
    INTEGER, OPTIONAL, INTENT(OUT) :: ierror
```

For consistency with the MPI 3.1 standard, I suggest that the "req" argument be renamed to "request" (which matters when specifying actual arguments using Fortran 2008 argument keywords).

Also, shouldn't the _flag_ argument have the ASYNCHRONOUS attribute?  (e.g., see the Fortran 2008 interface for MPI_COMM_IDUP in MPI 3.1, where the _newcomm_ argument has the ASYNCHRONOUS attribute)

**Comment by abouteiller** [comment]
@nathanweeks Thanks for the feedback. I will change the "req" to "request" for consistency.

I will check for the ASYNCHRONOUS.

**Comment by bosilca** [comment]
In order to prevent the Fortran compiler from doing unsafe optimizations all OUT arguments should be marked as ASYNCHRONOUS for non-blocking functions (as explained in Subsection "The Fortran ASYNCHRONOUS Attribute" page 643 in MPI 3.1). This applies to the flag argument in MPI_COMM_IAGREE.

**Comment by abouteiller** [comment]
Issue resolved
