### ISSUE TITLE
Provide a way for passive target RMA to get error notification

### ISSUE THREAD

**Issue by wesbland** [mpiwg-ft/ft-issues#2]
During the September '15 forum meeting, Jim Dinan raised the point that it will be tough for passive target RMA to use FT in its current version because there is no failure notification guaranteed until calling `MPI_WIN_UNLOCK_ALL`. He suggested that we may be able to do something with the combination of `MPI_WIN_FLUSH` or `MPI_WIN_FLUSH_LOCAL` that would guarantee failure notification for one of them, but not the other. 

For instance, if doing:

```
MPI_Get(...);
MPI_Win_flush_local(...);
```

we might be able to guarantee failure notification here.

I'm skeptical because it sounds like this would be introducing the very overhead that we've been trying to avoid.

**Comment by abouteiller** [comment]
History on this discussion can be found here:
https://bitbucket.org/bosilca/mpi3ft/issues/16/mpi_win_flush-error-reporting
https://bitbucket.org/bosilca/mpi3ft/pull-requests/57/adding-a-flush-advice-from-discussion-with/diff

Some discussion took place in this phone call: 
https://github.com/mpiwg-ft/ft-issues/wiki/2015-10-27
