### ISSUE TITLE
Overall Revamp of Error Handlers

### ISSUE THREAD

**Issue by wesbland** [mpiwg-ft/ft-issues#6]
In Portland (March 2015), Tony suggested that we should take a wider look at error handlers and investigate what we would change if we could start over with them. Having thought about this for a while, here's an initial list of things that we could improve:
- Get multiple MPI objects in a single error handler (Communicators, Windows, Files, Requests)
- Get multiple error codes in a single call to the error handler
- Allow the application/library to provide contextual information
- Pick which error classes we handle in a single function
- Combine the three error handler functions into a single one
- Add extensible struct/union/whatever to figure out what is impacted

**Comment by chadbrewbaker** [comment]
As an MPI user, my first concern is latency. When I do a reduce I want to know which nodes are giving me latency spikes. On a 10k node cluster if a handful of nodes are giving me 100x latency I want to drop them ASAP if they don't completely mess up my network topology.

I'm not convinced that changes to the error API should be made until we understand the error data. We need to apply the scientific method and get diagnostics on communicators that can be used to generate errors.

How do we do diagnostics without hurting performance?

Can we sum "stopwatches" from nodes so we don't have to care if clocks are in sync?

At what granularity do we measure? Personally I am a fan of the https://en.wikipedia.org/wiki/HBJ_model . Two values, time for the initial connection and total time.

Should diagnostics be turned on by default? To me the answer is yes if the diagnostic overhead is much lower than the network latency.

Ultimately I think we are going to get elastic communicators, especially at the COMM_WORLD level.

**Comment by wesbland** [comment]
I'm not sure I understand what you're asking for here @chadbrewbaker. If you're looking for performance data to determine the state of your system, that sort of information is already available via the MPI_T interface. The error handlers that we're discussing here are for dealing with an error listed by the error classes. When it is raised, MPI has already decided that it needs to report errors to the user. Here, we're talking about the API for the callback function where these errors are raised.

Performance errors like you're discussing haven't been something we've covered much in the MPI Standard. Again, there are some tools (such as MPI_T) to help you diagnose performance problems, but there isn't a mechanism for dropping processes from a job right now. It's something that we've briefly discussed in past FT discussions, but it was usually in the context of transient failures rather than poor performance.
